interface Data{
    id:number,
    img:string,
    title:string,
    prevPrice:string,
    newPrice:string,
    company:string,
    color:string,
    amount:string,
    category:string,
    choosedAmount:number,
    buttonText:string,
    total:number
}
const data:Data[]= [
  {
    id:1,
    img: 'https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg',
    title: 'Nike Air Monarch IV',
    prevPrice: '240,00$',
    newPrice: '200$',
    company: 'Nike',
    color: 'white',
    amount: '2 pairs',
    category: 'sneakers',
    buttonText:"add to cart",
    choosedAmount:1,
    total:200,
  },
  {
    id:2,
    img: 'https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg',
    title: 'Nike Air Vapormax Plus',
    prevPrice: '240,00$',
    newPrice: '200$',
    company: 'Nike',
    color: 'red',
    amount: '3 pairs',
    category: 'sneakers',
    buttonText:"add to cart",
    choosedAmount:1,
    total:200,
  },
  {
    id:3,
    img: 'https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg',
    title: 'Nike Waffle One Sneaker',
    prevPrice: '240,00$',
    newPrice: '200$',
    company: 'Nike',
    color: 'green',
    amount: '1 pair',
    category: 'sneakers',
    buttonText:"add to cart",
    choosedAmount:1,
    total:200,
  },
  {
    id:4,
    img: 'https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg',
    title: 'Nike Running Shoe',
    prevPrice: '240,00$',
    newPrice: '200$',
    company: 'Adidas',
    color: 'black',
    amount: '4 pairs',
    category: 'sneakers',
    buttonText:"add to cart",
    choosedAmount:1,
    total:200,
  },
  {
    id:5,
    img: 'https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg',
    title: 'Flat Slip On Pumps',
    prevPrice: '240,00$',
    newPrice: '200$',
    company: 'Vans',
    color: 'green',
    amount: '2 pairs',
    category: 'flats',
    buttonText:"add to cart",
    choosedAmount:1,
    total:200,
  },
  {
    id:6,
    img: 'https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg',
    title: 'Knit Ballet Flat',
    prevPrice: '140,00$',
    newPrice: '50$',
    company: 'Adidas',
    color: 'black',
    amount: '3 pairs',
    category: 'flats',
    buttonText:"add to cart",
    choosedAmount:1,
    total:50,
  },
  {
    id:7,
    img: 'https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg',
    title: 'Loafer Flats',
    prevPrice: '140,00$',
    newPrice: '50$',
    company: 'Vans',
    color: 'white',
    amount: '1 pair',
    category: 'flats',
    buttonText:"add to cart",
    choosedAmount:1,
    total:50,
  },
  {
    id:8,
    img: 'https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg',
    title: 'Nike Zoom Freak',
    prevPrice: '240,00$',
    newPrice: '200$',
    company: 'Nike',
    color: 'green',
    amount: '4 pairs',
    category: 'sneakers',
    buttonText:"add to cart",
    choosedAmount:1,
    total:200,
  },
  {
    id:9,
    img: 'https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg',
    title: "Nike Men's Sneaker",
    prevPrice: '240,00$',
    newPrice: '200$',
    company: 'Adidas',
    color: 'blue',
    amount: '2 pairs',
    category: 'sneakers',
    buttonText:"add to cart",
    choosedAmount:1,
    total:200,
  },
  {
    id:10,
    img: 'https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg',
    title: 'PUMA BLACK-OCE',
    prevPrice: '240,00$',
    newPrice: '150$',
    company: 'Puma',
    color: 'green',
    amount: '2 pairs',
    category: 'sneakers',
    buttonText:"add to cart",
    choosedAmount:1,
    total:150,
  },
  {
    id:11,
    img: 'https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg',
    title: 'Pacer Future Sneaker',
    prevPrice: '240,00$',
    newPrice: '150$',
    company: 'Puma',
    color: 'red',
    amount: '3 pairs',
    category: 'sneakers',
    buttonText:"add to cart",
    choosedAmount:1,
    total:150,
  },
  {
    id:12,
    img: 'https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg',
    title: 'Unisex-Adult Super',
    prevPrice: '240,00$',
    newPrice: '150$',
    company: 'Puma',
    color: 'black',
    amount: '1 pair',
    category: 'sneakers',
    buttonText:"add to cart",
    choosedAmount:1,
    total:150,
  },
  {
    id:13,
    img: 'https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg',
    title: 'Roma Basic Sneaker',
    prevPrice: '240,00$',
    newPrice: '150$',
    company: 'Puma',
    color: 'white',
    amount: '2 pairs',
    category: 'sneakers',
    buttonText:"add to cart",
    choosedAmount:1,
    total:150,
  },
  {
    id:14,
    img: 'https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg',
    title: 'Pacer Future Doubleknit',
    prevPrice: '240,00$',
    newPrice: '150$',
    company: 'Puma',
    color: 'black',
    amount: '2 pairs',
    category: 'sneakers',
    buttonText:"add to cart",
    choosedAmount:1,
    total:150,
  },
  {
    id:15,
    img: 'https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg',
    title: 'Fusion Evo Golf Shoe',
    prevPrice: '140,00$',
    newPrice: '100$',
    company: 'Puma',
    color: 'green',
    amount: '2 pairs',
    category: 'sneakers',
    buttonText:"add to cart",
    choosedAmount:1,
    total:100,
  },
  {
    id:16,
    img: 'https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg',
    title: 'Rainbow Chex Skate',
    prevPrice: '140,00$',
    newPrice: '100$',
    company: 'Vans',
    color: 'red',
    amount: '2 pairs',
    category: 'flats',
    buttonText:"add to cart",
    choosedAmount:1,
    total:100,
  },
  {
    id:17,
    img: 'https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg',
    title: 'Low-Top Trainers',
    prevPrice: '140,00$',
    newPrice: '100$',
    company: 'Vans',
    color: 'white',
    amount: '3 pairs',
    category: 'sandals',
    buttonText:"add to cart",
    choosedAmount:1,
    total:100,
  },
  {
    id:18,
    img: 'https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg',
    title: 'Vans Unisex Low-Top',
    prevPrice: '140,00$',
    newPrice: '100$',
    company: 'Vans',
    color: 'blue',
    amount: '1 pair',
    category: 'sandals',
    buttonText:"add to cart",
    choosedAmount:1,
    total:100,
  },
  {
    id:19,
    img: 'https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg',
    title: 'Classic Bandana Sneakers',
    prevPrice: '140,00$',
    newPrice: '50$',
    company: 'Nike',
    color: 'black',
    amount: '2 pairs',
    category: 'sandals',
    buttonText:"add to cart",
    choosedAmount:1,
    total:50,
  },
  {
    id:20,
    img: 'https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg',
    title: 'Chunky High Heel',
    prevPrice: '140,00$',
    newPrice: '50$',
    company: 'Vans',
    color: 'black',
    amount: '4 pairs',
    category: 'heels',
    buttonText:"add to cart",
    choosedAmount:1,
    total:50,
  },
  {
    id:21,
    img: 'https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg',
    title: 'Slip On Stiletto High Heel',
    prevPrice: '140,00$',
    newPrice: '100$',
    company: 'puma',
    color: 'black',
    amount: '2 pairs',
    category: 'heels',
    buttonText:"add to cart",
    choosedAmount:1,
    total:100,
  },
  {
    id:22,
    img: 'https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg',
    title: 'DREAM PAIRS Court Shoes',
    prevPrice: '240,00$',
    newPrice: '150$',
    company: 'Nike',
    color: 'red',
    amount: '2 pairs',
    category: 'heels',
    buttonText:"add to cart",
    choosedAmount:1,
    total:150,
  },
  {
    id:23,
    img: 'https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg',
    title: 'Low Mid Block Heels',
    prevPrice: '240,00$',
    newPrice: '200$',
    company: 'Nike',
    color: 'black',
    amount: '3 pairs',
    category: 'heels',
    buttonText:"add to cart",
    choosedAmount:1,
    total:200,
  },
  {
    id:24,
    img: 'https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg',
    title: 'Chunky High Heel',
    prevPrice: '140,00$',
    newPrice: '50$',
    company: 'Adidas',
    color: 'black',
    amount: '2 pairs',
    category: 'heels',
    buttonText:"add to cart",
    choosedAmount:1,
    total:50,
  },
  {
    id:25,
    img: 'https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg',
    title: 'Amore Fashion Stilettos',
    prevPrice: '240,00$',
    newPrice: '150$',
    company: 'Adidas',
    color: 'white',
    amount: '4 pairs',
    category: 'heels',
    buttonText:"add to cart",
    choosedAmount:1,
    total:150,
  },
  {
    id:26,
    img: 'https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg',
    title: 'Bridal Sandals Glitter',
    prevPrice: '140,00$',
    newPrice: '50$',
    company: 'Adidas',
    color: 'black',
    amount: '2 pairs',
    category: 'heels',
    buttonText:"add to cart",
    choosedAmount:1,
    total:50,
  },
  {
    id:27,
    img: 'https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg',
    title: 'Wedding Prom Bridal',
    prevPrice: '140,00$',
    newPrice: '50$',
    company: 'Adidas',
    color: 'black',
    amount: '2 pairs',
    category: 'flats',
    buttonText:"add to cart",
    choosedAmount:1,
    total:50,
  }
]

  
  export default data;